/* Generated by scripts/build_home.py from each scenes/NAME/scene.js. Edit those. */
/* scenes/engine */
(function () {
  try {
    var sec = document.getElementById('engine');
    if (!sec) return;
    var root = document.documentElement;
        var stage = sec.querySelector('.eng-stage');
    var head = sec.querySelector('.eng-head');
    var word = sec.querySelector('.eng-word');
    var orb = sec.querySelector('.eng-orb .core');
    var img = sec.querySelector('.eng-device img');
    var flip = sec.getAttribute('data-flip') === '1';
    var ticking = false, step = 0, isWord = false, isLanded = false, wordCss = '', wordW = 0, wordH = 0, headBottom = 0;
    // Plays once, like a film, when the stage is half in view, then holds on the last frame.
    var DUR = 7000, t0 = 0, done = false;
    // Where "Good to go" sits on the 400 x 870 capture: centre and width.
    var TX = 144 / 400, TY = 284 / 870, TW = 248 / 400;
    function c01(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function seg(p, a, b) { return c01((p - a) / (b - a)); }
    function ease(t) { return t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2; }
    // Only changed values are written: an unchanged write still restyles the whole scene.
    var vals = {};
    function set(k, v) { var s = typeof v === 'number' ? v.toFixed(3) : v; if (vals[k] !== s) { vals[k] = s; sec.style.setProperty(k, s); } }
    // Geometry for the film, read once (and on resize) so no frame ever forces a layout.
    // G.dev*: the phone at rest; G.img*: the capture inside it; G.orb*: the orb relative
    // to the board's centre at full size. Frames map these through the current transforms.
    var G = null;
    function measure() {
      wordW = word.offsetWidth; wordH = word.offsetHeight;
      head.style.transform = 'none';
      headBottom = head.offsetTop + head.offsetHeight;
      head.style.transform = '';
      set('--dev-top', (headBottom + 18) + 'px');
      var vh0 = stage.clientHeight || window.innerHeight, vw0 = window.innerWidth;
      var room = vh0 - headBottom - 18 - (vw0 < 900 ? 44 : 28);
      set('--dev-w', Math.max(150, Math.min(vw0 * .66, 360, room / 2.2)) + 'px');
      var caps = sec.querySelector('.eng-caps');
      var capsTop = vh0 - (caps ? caps.offsetHeight : 90) - Math.max(22, vh0 * .03);
      var avail = capsTop - headBottom - 28;
      var bw = Math.max(240, Math.min(vw0 - 32, 600, (avail - 44) / 1.05 + 44));
      set('--board-w', bw + 'px');
      set('--board-y', ((headBottom + capsTop) / 2) + 'px');
      // Read the resting frame: board risen, nothing faded, phone in place.
      var keep = ['--rise', '--fade', '--dev'].map(function (k) { return sec.style.getPropertyValue(k); });
      sec.style.setProperty('--rise', '1'); sec.style.setProperty('--fade', '0'); sec.style.setProperty('--dev', '1');
      var st = stage.getBoundingClientRect(), dev = sec.querySelector('.eng-device').getBoundingClientRect();
      var bd = sec.querySelector('.eng-board').getBoundingClientRect();
      var ir = img ? img.getBoundingClientRect() : dev, o = orb ? orb.getBoundingClientRect() : bd;
      G = {
        w: st.width, h: st.height,
        dcx: dev.left - st.left + dev.width / 2, dcy: dev.top - st.top + dev.height / 2,
        tx: ir.left - st.left + ir.width * TX, ty: ir.top - st.top + ir.height * TY, tw: ir.width * TW,
        bcx: bd.left - st.left + bd.width / 2, bcy: bd.top - st.top + bd.height / 2,
        ox: o.left + o.width / 2 - (bd.left + bd.width / 2), oy: o.top + o.height / 2 - (bd.top + bd.height / 2)
      };
      ['--rise', '--fade', '--dev'].forEach(function (k, i) { if (keep[i]) sec.style.setProperty(k, keep[i]); else sec.style.removeProperty(k); });
    }
    function clear() {
      ['--a', '--b', '--c', '--d', '--hy', '--rise', '--fade', '--dev', '--bx', '--by', '--bs', '--bo', '--glow', '--mk', '--dev-top', '--dev-w', '--board-w', '--board-y'].forEach(function (k) { sec.style.removeProperty(k); });
      sec.removeAttribute('data-step'); sec.classList.remove('is-word', 'is-landed');
      word.style.transform = ''; word.style.opacity = '';
      step = 0; isWord = false; isLanded = false; wordCss = ''; vals = {};
    }
    function update() {
      ticking = false;
      if (!root.classList.contains('motion')) { if (step) clear(); return; }
      if (!wordW || !G) measure();
      var p = done ? 1 : t0 ? c01((performance.now() - t0) / DUR) : 0;
      if (p >= 1) done = true;
      set('--hy', 1 - ease(seg(p, 0, .16)));
      set('--rise', ease(seg(p, .03, .2)));
      set('--a', seg(p, .12, .32));
      set('--b', seg(p, .27, .42));
      set('--c', seg(p, .4, .54));
      set('--d', seg(p, .5, .58));
      set('--fade', ease(seg(p, .56, .68)));
      var dev = ease(seg(p, .7, .86));
      set('--dev', dev);
      var s = p < .27 ? 1 : p < .46 ? 2 : p < .74 ? 3 : 4;
      if (s !== step) { step = s; sec.setAttribute('data-step', String(s)); }
      var w = p > .55;
      if (w !== isWord) { isWord = w; sec.classList.toggle('is-word', w); }
      var landed = p > .88;
      if (landed !== isLanded) { isLanded = landed; sec.classList.toggle('is-landed', landed); }

      // Bloom: a burst of light where the three streams meet.
      var bl = seg(p, .55, .78);
      if (bl > 0 && bl < 1) {
        var bsc = 1 - .14 * ease(seg(p, .56, .68));
        set('--bx', (G.bcx + G.ox * bsc) + 'px');
        set('--by', (G.bcy + G.oy * bsc) + 'px');
      }
      set('--bs', bl <= 0 ? 0 : .05 + Math.sin(Math.min(bl, 1) * Math.PI * .5) * 2.4);
      set('--bo', bl <= 0 || bl >= 1 ? 0 : Math.sin(bl * Math.PI) * .9);

      // The word: appears big in the middle, then lands on the real screen.
      var wa = ease(seg(p, .6, .7));
      set('--glow', Math.sin(seg(p, .62, .82) * Math.PI));
      var cx = G.w / 2, cy = G.h * .52;
      var k = ease(seg(p, .74, .9));
      var s0 = .82 + .18 * wa, x = cx, y = cy, sc = s0, op = wa;
      if (k > 0) {
        if (flip) {
          // Where "Good to go" sits on the capture right now: the resting spot mapped
          // through the phone's current rise and scale (about its own centre).
          var ds = .9 + dev * .1, dy = (1 - dev) * .7 * G.h;
          var tx = G.dcx + (G.tx - G.dcx) * ds, ty = G.dcy + (G.ty - G.dcy) * ds + dy;
          var ts = (G.tw * ds) / wordW;
          x = cx + (tx - cx) * k; y = cy + (ty - cy) * k; sc = s0 + (ts - s0) * k;
          op = wa * (1 - seg(p, .9, .95));
        } else {
          y = cy - k * G.h * .08; sc = s0 * (1 - .3 * k); op = wa * (1 - k);
        }
      }
      set('--mk', 1 - seg(p, .895, .93));
      var css = op.toFixed(3) + '|translate3d(' + (x - wordW * sc / 2).toFixed(1) + 'px,' + (y - wordH * sc / 2).toFixed(1) + 'px,0) scale(' + sc.toFixed(4) + ')';
      if (css !== wordCss) { wordCss = css; var cut = css.indexOf('|'); word.style.opacity = css.slice(0, cut); word.style.transform = css.slice(cut + 1); }
    }
    function frame() { update(); if (t0 && !done) requestAnimationFrame(frame); }
    function play() { if (t0 || done) return; t0 = performance.now(); requestAnimationFrame(frame); }
    function redraw() { if (!ticking) { ticking = true; requestAnimationFrame(update); } }
    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (es) { if (es[0].isIntersecting) play(); }, { threshold: .5 }).observe(stage);
      // Scrolled away mid-film: jump to the last frame instead of animating off screen.
      new IntersectionObserver(function (es) { if (!es[0].isIntersecting && t0 && !done) { done = true; redraw(); } }).observe(stage);
    } else { done = true; }
    window.addEventListener('resize', function () { wordW = 0; redraw(); }, { passive: true });
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(function () { wordW = 0; redraw(); });
    update();
  } catch (e) {
    try { var s2 = document.getElementById('engine'); s2.removeAttribute('style'); s2.classList.add('eng-off'); } catch (e2) {}
  }
})();

/* scenes/flyover */
/* Flyover scene: scroll flies a camera over the contour model. The route draws
   with the runner on its head, the camera follows it, eases to a stop at the
   fastest split and at the top of the climb, then pulls back up and away while
   the real capture rises in. Only transforms and opacity change per frame.
   Without .motion the CSS defaults are the finished frame; this file then only
   pins the runner and the two callouts to it. On any error it steps aside. */
(function () {
  var sec = document.getElementById('flyover');
  if (!sec) return;
  var root = document.documentElement;
  var stage, pin, cam, world, puck, copy, chips, layers, nums, routeEl;
  var PX = [], PY = [], HD = [], Z, E, PACE, HR, pS, pC, NS = 300;
  var cfg = {}, alive = true, ticking = false, mode = '', copyIn = false, saved = [];

  function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
  function ss(a, b, x) { x = clamp((x - a) / (b - a)); return x * x * (3 - 2 * x); }
  function lerp(a, b, k) { return a + (b - a) * k; }
  function bump(a, m, b, x) { return x < m ? ss(a, m, x) : 1 - ss(m, b, x); }
  function sample(arr, p) {
    var f = clamp(p) * (arr.length - 1), i = Math.floor(f), k = f - i;
    return i >= arr.length - 1 ? arr[arr.length - 1] : arr[i] + (arr[i + 1] - arr[i]) * k;
  }
  function list(name) { return (sec.getAttribute('data-' + name) || '0').split(',').map(Number); }
  function num(cs, name, fallback) { var v = parseFloat(cs.getPropertyValue(name)); return isNaN(v) ? fallback : v; }
  function mmss(s) { s = Math.round(s); var m = Math.floor(s / 60), r = s % 60; return m + ':' + (r < 10 ? '0' : '') + r; }
  function put(el, name, v) { el.style.setProperty(name, v); }

  function setup() {
    stage = sec.querySelector('.fo-stage');
    pin = sec.querySelector('.fo-pin');
    cam = sec.querySelector('.fo-cam');
    world = sec.querySelector('.fo-world');
    puck = sec.querySelector('.fo-puck');
    copy = sec.querySelector('.fo-copy');
    routeEl = document.getElementById('flyover-r');
    chips = [].slice.call(sec.querySelectorAll('.fo-chip'));
    layers = [].slice.call(sec.querySelectorAll('.fo-l[data-r]')).map(function (el) {
      var r = el.getAttribute('data-r').split(' ').map(Number);
      return { el: el, lo: r[0], hi: r[1], d: -1 };
    });
    nums = {};
    [].slice.call(sec.querySelectorAll('.fo-hud b[data-k]')).forEach(function (b) {
      nums[b.getAttribute('data-k')] = { el: b, v: b.textContent };
    });
    Z = list('z'); E = list('e'); PACE = list('pace'); HR = list('hr');
    pS = Number(sec.getAttribute('data-ps')) || 0.25;
    pC = Number(sec.getAttribute('data-pc')) || 0.7;

    var len = routeEl.getTotalLength(), ang = [], i, j;
    for (i = 0; i <= NS; i++) {
      var q = routeEl.getPointAtLength(len * i / NS);
      PX.push(q.x); PY.push(q.y);
    }
    for (i = 0; i < NS; i++) ang.push(Math.atan2(PY[i + 1] - PY[i], PX[i + 1] - PX[i]));
    ang.push(ang[NS - 1]);
    for (i = 1; i <= NS; i++) {            // unwrap
      while (ang[i] - ang[i - 1] > Math.PI) ang[i] -= 2 * Math.PI;
      while (ang[i] - ang[i - 1] < -Math.PI) ang[i] += 2 * Math.PI;
    }
    var sig = 26, w = [];                    // wide kernel: switchbacks average out
    for (j = -3 * sig; j <= 3 * sig; j++) w.push(Math.exp(-j * j / (2 * sig * sig)));
    for (i = 0; i <= NS; i++) {
      var s = 0, ws = 0;
      for (j = -3 * sig; j <= 3 * sig; j++) {
        var k = Math.min(NS, Math.max(0, i + j)), wt = w[j + 3 * sig];
        s += ang[k] * wt; ws += wt;
      }
      HD.push(-90 - (s / ws) * 180 / Math.PI);
    }
    [world, puck, stage].concat(chips, layers.map(function (l) { return l.el; })).forEach(function (el) {
      saved.push([el, el.getAttribute('style')]);
    });
  }

  function readConfig() {
    var cs = getComputedStyle(world), cs2 = getComputedStyle(sec), cc = getComputedStyle(cam);
    cfg.W = world.offsetWidth;
    cfg.u = cfg.W / 1000;
    cfg.dz = cfg.W * num(cs2, '--dzk', 0.018);
    cfg.oZm = num(cs2, '--o-zm', 0.86);
    cfg.fZm = num(cs2, '--f-zm', 1.8);
    cfg.fCy = num(cs2, '--f-cy', 0.15);
    cfg.eTilt = num(cs, '--e-tilt', 52);
    cfg.eHd = num(cs, '--e-hd', -18);
    cfg.eZm = num(cs, '--e-zm', 0.86);
    cfg.eFx = num(cs, '--e-fx', 520);
    cfg.eFy = num(cs, '--e-fy', 540);
    cfg.eCx = num(cs, '--e-cx', 0);
    cfg.eCy = num(cs, '--e-cy', 0.1);
    cfg.endChips = num(cs2, '--end-chips', 1);
    cfg.eCyPx = cfg.eCy * cfg.W;
    if (cfg.vw < 900 && copy.offsetHeight) {
      // Phones: fit the finished model into the space the copy leaves free.
      var below = copy.offsetTop + copy.offsetHeight, free = cfg.vh - below;
      var k = Math.min(1.2, Math.max(0.7, free / 454));
      cfg.eZm *= k;
      cfg.eCyPx = below + free * 0.6 - cfg.vh / 2;
      if (free < 400) cfg.endChips = 0;
    }
    cfg.eHdU = cfg.eHd + 360 * Math.round((HD[NS] - cfg.eHd) / 360);
    cfg.d = parseFloat(cc.perspective) || 1500;
    var po = cc.perspectiveOrigin.split(' ');
    cfg.vw = cam.clientWidth;
    cfg.vh = cam.clientHeight;
    cfg.pox = parseFloat(po[0]); if (isNaN(cfg.pox)) cfg.pox = cfg.vw / 2;
    cfg.poy = parseFloat(po[1]); if (isNaN(cfg.poy)) cfg.poy = cfg.vh / 2;
  }

  // Route progress: eases into a full stop at the split and at the summit.
  var K = null;
  function progress(t) {
    if (!K) K = [[0.08, 0], [0.24, pS], [0.31, pS], [0.58, pC], [0.66, pC], [0.79, 1]];
    if (t <= K[0][0]) return 0;
    for (var i = 1; i < K.length; i++) {
      if (t <= K[i][0]) return lerp(K[i - 1][1], K[i][1], ss(K[i - 1][0], K[i][0], t));
    }
    return 1;
  }

  // The camera for a moment t of the flight. pose(1) equals the CSS defaults.
  function pose(t) {
    var p = progress(t), pl = progress(t - 0.014);
    var dive = ss(0.02, 0.2, t), away = ss(0.74, 0.95, t);
    var atTop = bump(0.55, 0.62, 0.7, t), atSplit = bump(0.21, 0.275, 0.34, t);
    var hx = sample(PX, pl), hy = sample(PY, pl), hz = sample(Z, pl);
    var hd = lerp(HD[0] + 46 * (1 - ss(0, 0.2, t)), sample(HD, pl), dive);
    return {
      p: p,
      fx: lerp(lerp(515, hx, dive), cfg.eFx, away),
      fy: lerp(lerp(560, hy, dive), cfg.eFy, away),
      fz: lerp(hz * dive, 0, away),
      hd: lerp(hd, cfg.eHdU, away),
      zm: lerp(lerp(cfg.oZm, cfg.fZm, dive), cfg.eZm, away) * (1 - 0.2 * atTop) * (1 + 0.06 * atSplit),
      tilt: lerp(lerp(48, 62, dive) - 9 * atTop - 12 * ss(0.6, 0.7, t), cfg.eTilt, away),
      cx: cfg.eCx * cfg.W * away,
      cy: lerp((lerp(0.06, cfg.fCy, dive) - 0.1 * atTop) * cfg.vh, cfg.eCyPx, away)
    };
  }

  // Where a point of the model lands on the stage, the same chain the CSS uses.
  function project(c, xw, yw, lv) {
    var x = (xw - 500) * cfg.u + (500 - c.fx) * cfg.u;
    var y = (yw - 500) * cfg.u + (500 - c.fy) * cfg.u;
    var z = lv * cfg.dz - c.fz * cfg.dz;
    x *= c.zm; y *= c.zm; z *= c.zm;
    var a = c.hd * Math.PI / 180, ca = Math.cos(a), sa = Math.sin(a);
    var x1 = x * ca - y * sa, y1 = x * sa + y * ca;
    var b = c.tilt * Math.PI / 180, cb = Math.cos(b), sb = Math.sin(b);
    var y2 = y1 * cb - z * sb, z2 = y1 * sb + z * cb;
    var X = cfg.vw / 2 + x1 + c.cx, Y = cfg.vh / 2 + y2 + c.cy;
    var s = cfg.d / Math.max(cfg.d - z2, 1);
    return [cfg.pox + (X - cfg.pox) * s, cfg.poy + (Y - cfg.poy) * s];
  }

  function pinTo(el, c, xw, yw, lv) {
    var q = project(c, xw, yw, lv);
    put(el, '--sx', q[0].toFixed(1) + 'px');
    put(el, '--sy', q[1].toFixed(1) + 'px');
  }

  function pins(c, p) {
    pinTo(puck, c, sample(PX, p), sample(PY, p), sample(Z, p));
    pinTo(chips[0], c, sample(PX, pS), sample(PY, pS), sample(Z, pS));
    pinTo(chips[1], c, sample(PX, pC), sample(PY, pC), sample(Z, pC));
  }

  function applyWorld(c) {
    put(world, '--tilt', c.tilt.toFixed(2) + 'deg');
    put(world, '--hd', c.hd.toFixed(2) + 'deg');
    put(world, '--zm', c.zm.toFixed(4));
    put(world, '--px', ((500 - c.fx) * cfg.u).toFixed(1) + 'px');
    put(world, '--py', ((500 - c.fy) * cfg.u).toFixed(1) + 'px');
    put(world, '--pz', (-c.fz * cfg.dz).toFixed(1) + 'px');
    put(world, '--cx', c.cx.toFixed(1) + 'px');
    put(world, '--cy', c.cy.toFixed(1) + 'px');
  }

  function render(t) {
    var c = pose(t), p = c.p;
    applyWorld(c);
    pins(c, p);

    layers.forEach(function (l) {
      var d = 1 - Math.min(l.hi, Math.max(l.lo, p));
      if (Math.abs(d - l.d) > 0.0002) { l.d = d; put(l.el, '--d', d.toFixed(4)); }
    });

    var end1 = ss(0.86, 0.93, t) * cfg.endChips, end2 = ss(0.88, 0.95, t);
    put(chips[0], '--a', Math.max(ss(0.19, 0.235, t) * (1 - ss(0.35, 0.4, t)), end1).toFixed(3));
    put(chips[1], '--a', Math.max(ss(0.53, 0.575, t) * (1 - ss(0.69, 0.74, t)), end2).toFixed(3));

    put(puck, '--pa', (1 - ss(0.8, 0.88, t)).toFixed(3));
    put(stage, '--hud', (ss(0.015, 0.07, t) * (1 - ss(0.72, 0.78, t))).toFixed(3));
    put(stage, '--p', p.toFixed(4));
    put(stage, '--ct', Math.max(1 - ss(0.05, 0.13, t), ss(0.76, 0.88, t)).toFixed(3));
    put(stage, '--cp', ss(0.79, 0.91, t).toFixed(3));
    put(stage, '--pr', ss(0.78, 0.97, t).toFixed(4));
    var want = t < 0.09 || t > 0.75;
    if (want !== copyIn) { copyIn = want; copy.classList.toggle('in', want); }

    text('e', String(Math.round(sample(E, p))));
    text('pace', mmss(sample(PACE, p)));
    text('hr', String(Math.round(sample(HR, p))));
  }

  function text(k, v) {
    var n = nums[k];
    if (n && n.v !== v) { n.v = v; n.el.textContent = v; }
  }

  function reset() {
    saved.forEach(function (it) {
      if (it[1] === null) it[0].removeAttribute('style'); else it[0].setAttribute('style', it[1]);
    });
    layers.forEach(function (l) { l.d = -1; });
    copy.classList.add('in');
    copyIn = true;
  }

  function frame() {
    ticking = false;
    if (!alive) return;
    try {
      var moving = root.classList.contains('motion');
      if (!moving) {
        // The finished frame: only the runner and the callouts need placing.
        if (mode !== 'still') {
          reset(); mode = 'still'; readConfig();
          var c = pose(1); applyWorld(c); pins(c, 1);
          if (!cfg.endChips) put(chips[0], 'display', 'none');
        }
        return;
      }
      if (!G) measure();
      var top = G.top - SY, vh = G.vh;
      if (top + G.h < -200 || top > vh + 200) return;
      if (mode !== 'fly') { mode = 'fly'; readConfig(); copyIn = false; copy.classList.remove('in'); }
      var span = G.h - vh;
      render(span > 0 ? clamp(-top / span) : 1);
    } catch (e) {
      alive = false;
      try { reset(); sec.classList.remove('fo-js'); } catch (e2) { /* the static frame stays */ }
    }
  }
  // The pin's place is read on load and resize only, and scrollY in the scroll event,
  // so a frame never forces a style or layout pass. Far from the scene, scrolling does nothing.
  var G = null, SY = window.scrollY, near = true;
  function measure() {
    var r = pin.getBoundingClientRect();
    G = { top: r.top + window.scrollY, h: r.height, vh: window.innerHeight };
  }
  function remeasure() { mode = ''; G = null; SY = window.scrollY; request(); }
  function request() {
    if (ticking) return;
    ticking = true;
    requestAnimationFrame(frame);
    setTimeout(function () { if (ticking) frame(); }, 250);
  }

  try {
    setup();
    sec.classList.add('fo-js');
    window.addEventListener('scroll', function () { SY = window.scrollY; if (near) request(); }, { passive: true });
    window.addEventListener('resize', remeasure, { passive: true });
    window.addEventListener('load', remeasure);
    if ('ResizeObserver' in window) new ResizeObserver(function () { G = null; SY = window.scrollY; request(); }).observe(document.body);
    if ('IntersectionObserver' in window) new IntersectionObserver(function (es) {
      near = es[0].isIntersecting; if (near) { SY = window.scrollY; request(); }
    }, { rootMargin: '100% 0px' }).observe(pin);
    request();
  } catch (e) {
    alive = false;
  }
})();

/* scenes/planner */
(function () {
  try {
    var sec = document.getElementById('planner');
    if (!sec) return;
    var root = document.documentElement;
    var stage = sec.querySelector('.pl-stage');
    var head = sec.querySelector('.pl-head');
    var caps = sec.querySelector('.pl-caps');
    var route = sec.querySelector('#planner-route');
    var glow = sec.querySelector('.pl-glow');
    var casing = sec.querySelector('.pl-case');
    var dot = sec.querySelector('#planner-head');
    var finger = sec.querySelector('#planner-finger');
    var taps = [].slice.call(sec.querySelectorAll('.pl-tap'));
    var num = sec.querySelector('.pl-num');
    var wdist = sec.querySelector('.pl-wd-num');
    var km = parseFloat(num && num.getAttribute('data-km')) || 6.4;
    var comma = num && num.textContent.indexOf(',') > -1;
    var len = route.getTotalLength();
    // Where along the line (0..1) each tap lands: start, bridge, park edge, summit.
    var TAP_AT = [0, 0, 0, 0];
    var TAPS_XY = [[505, 588], [262, 398], [190, 256], [452, 104]];
    (function () {
      var n = 240, best = [1e9, 1e9, 1e9, 1e9];
      for (var i = 0; i <= n; i++) {
        var pt = route.getPointAtLength(len * i / n);
        for (var k = 0; k < 4; k++) {
          var d = Math.hypot(pt.x - TAPS_XY[k][0], pt.y - TAPS_XY[k][1]);
          if (d < best[k]) { best[k] = d; TAP_AT[k] = i / n; }
        }
      }
    })();
    var step = 0, measured = false, last = -1;

    function c01(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function seg(p, a, b) { return c01((p - a) / (b - a)); }
    function ease(t) { return t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2; }
    function out(t) { return 1 - Math.pow(1 - t, 3); }
    function back(t) { var c = 1.6; return t <= 0 ? 0 : t >= 1 ? 1 : 1 + (c + 1) * Math.pow(t - 1, 3) + c * Math.pow(t - 1, 2); }
    function set(k, v) { sec.style.setProperty(k, typeof v === 'number' ? v.toFixed(4) : v); }

    function measure() {
      var vw = window.innerWidth, vh = window.innerHeight, phone = vw < 900, wide = vw >= 1100;
      var top, h, ww;
      if (wide) {
        // Words on the left: the headline block and the caption sit centred as a pair.
        var hh = head.offsetHeight, ch = caps.offsetHeight;
        var ht = Math.max(84, (vh - hh - ch - 28) / 2);
        set('--head-top', ht + 'px');
        set('--caps-top', (ht + hh + 28) + 'px');
        top = 78; h = vh - top - 34;
        ww = sec.querySelector('.pl-world').offsetWidth || (vw * .6);
      } else {
        var hb = head.offsetTop + head.offsetHeight;
        top = hb + (phone ? 14 : 22);
        var bottom = vh - caps.offsetHeight - Math.max(22, vh * .032) - (phone ? 12 : 20);
        h = Math.max(220, bottom - top);
        ww = vw;
      }
      set('--world-top', top + 'px');
      set('--world-h', h + 'px');
      // Map: as big as the room allows; tilted, it reads wider than it is.
      var mw = Math.min(ww - (phone ? 24 : 60), wide ? 720 : 620, h * .9 * 600 / 640);
      set('--map-px', Math.max(220, mw) + 'px');
      // Watch: tall enough to read the turn from across the room.
      var wpx = Math.min(phone ? vw * .58 : 300, h / (1.19 * 1.42));
      set('--watch-px', Math.max(130, wpx) + 'px');
      set('--away-y', (h * .06) + 'px');
      measured = true;
    }
    function clear() {
      ['--in', '--draw', '--tilt', '--pan', '--map-o', '--pin-o', '--p1', '--p2', '--p3', '--hud', '--away', '--wrist', '--ph', '--world-top', '--world-h', '--map-px', '--watch-px', '--away-y', '--head-top', '--caps-top'].forEach(function (k) { sec.style.removeProperty(k); });
      sec.removeAttribute('data-step');
      route.style.strokeDasharray = route.style.strokeDashoffset = '';
      glow.style.strokeDasharray = glow.style.strokeDashoffset = '';
      casing.style.strokeDasharray = casing.style.strokeDashoffset = '';
      step = 0; measured = false; last = -1;
    }
    function fmt(v) { var s = v.toFixed(1); return comma ? s.replace('.', ',') : s; }

    function update() {

      if (!root.classList.contains('motion')) { if (step) clear(); return; }
      if (!measured) measure();
      var p = film;
      if (Math.abs(p - last) < .0004 && step) return;
      last = p;

      // Beat 1: draw (0 to .36)
      set('--in', out(seg(p, 0, .1)));
      set('--hud', out(seg(p, .06, .12)));
      var d = seg(p, .1, .34);
      var drawn = ease(d);
      // The finger hops tap to tap; the line follows to the next tap.
      var hop = drawn * 3, k = Math.min(2, Math.floor(hop)), f = hop - k;
      var at = TAP_AT[k] + (TAP_AT[k + 1] - TAP_AT[k]) * c01(f * 1.25);
      if (d >= 1) at = 1;
      var off = len * (1 - at);
      route.style.strokeDasharray = len + ' ' + len; route.style.strokeDashoffset = off;
      casing.style.strokeDasharray = len + ' ' + len; casing.style.strokeDashoffset = off;
      glow.style.strokeDasharray = len + ' ' + len; glow.style.strokeDashoffset = off;
      var pt = route.getPointAtLength(len * at);
      dot.setAttribute('cx', pt.x.toFixed(1)); dot.setAttribute('cy', pt.y.toFixed(1));
      dot.style.opacity = d > 0 && d < 1 ? 1 : 0;
      // Finger sits on the tap it is about to make.
      var fi = d <= 0 ? 0 : Math.min(3, f > .8 ? k + 1 : k);
      if (d >= 1) fi = 3;
      finger.setAttribute('transform', 'translate(' + TAPS_XY[fi][0] + ' ' + TAPS_XY[fi][1] + ')');
      finger.style.opacity = (p > .08 && p < .36) ? .95 : 0;
      for (var i = 0; i < 4; i++) {
        var tapAt = i === 0 ? 0 : i / 3;
        var on = d > 0 && drawn >= tapAt - .001;
        var since = c01((drawn - tapAt) * 6);
        var rip = taps[i].querySelector('.pl-rip'), wp = taps[i].querySelector('.pl-wp');
        wp.style.opacity = on ? 1 : 0;
        rip.style.opacity = on ? (1 - since) * .9 : 0;
        rip.setAttribute('r', (6 + since * 22).toFixed(1));
      }
      // Like the app: the figure updates when a leg lands, it does not tick.
      var legs = d <= 0 ? 0 : d >= 1 ? 3 : Math.min(3, Math.floor(drawn * 3 + .2));
      var shown = km * (legs ? TAP_AT[legs] : 0);
      if (num && num.getAttribute('data-v') !== String(legs)) { num.setAttribute('data-v', String(legs)); num.textContent = fmt(shown); num.parentNode.classList.remove('pl-bump'); void num.offsetWidth; if (legs) num.parentNode.classList.add('pl-bump'); }

      // Beat 2: tilt into 3D, sights stand up (.36 to .66)
      set('--tilt', ease(seg(p, .36, .48)) * (1 - ease(seg(p, .66, .76))));
      set('--pan', ease(seg(p, .42, .66)) * (1 - ease(seg(p, .66, .76))));
      set('--p1', back(seg(p, .44, .5)) * (1 - seg(p, .66, .72)));
      set('--p2', back(seg(p, .5, .56)) * (1 - seg(p, .66, .72)));
      set('--p3', back(seg(p, .56, .62)) * (1 - seg(p, .66, .72)));

      // Beat 3: map settles back, the Watch rises (.68 to 1)
      var aw = ease(seg(p, .66, .8));
      set('--away', aw);
      set('--map-o', 1 - aw * .9);
      set('--pin-o', 1 - seg(p, .66, .7));
      set('--ph', out(seg(p, .7, .84)));
      set('--wrist', out(seg(p, .74, .88)));
      var turn = seg(p, .86, .97);
      sec.classList.toggle('pl-turned', turn >= 1);
      if (wdist) {
        var m = turn >= 1 ? 300 : Math.max(10, Math.round((1 - turn) * 12) * 10);
        wdist.textContent = String(m);
      }

      var s = p < .37 ? 1 : p < .67 ? 2 : 3;
      if (s !== step) { step = s; sec.setAttribute('data-step', String(s)); }
    }
    // A film: it plays once when the stage is half in view and holds its last frame.
    var D = 9500, film = 0, t0 = 0, raf = 0;
    var again = sec.querySelector('.pl-again');
    function tick(now) {
      raf = 0;
      if (!root.classList.contains('motion')) { film = 0; t0 = 0; update(); return; }
      film = c01((now - t0) / D);
      update();
      if (film < 1) raf = requestAnimationFrame(tick);
      else sec.classList.add('pl-done');
    }
    function play() {
      if (raf) cancelAnimationFrame(raf);
      sec.classList.remove('pl-done');
      film = 0; last = -1; t0 = performance.now();
      raf = requestAnimationFrame(tick);
    }
    if (again) again.addEventListener('click', play);
    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (es) {
        if (!t0 && es[0].intersectionRatio >= .5 && root.classList.contains('motion')) play();
      }, { threshold: [0, .5] }).observe(stage);
    } else { film = 1; }
    window.addEventListener('resize', function () { measured = false; last = -1; if (!raf) update(); }, { passive: true });
    new MutationObserver(function () { measured = false; last = -1; if (!root.classList.contains('motion')) { t0 = 0; film = 0; } update(); }).observe(root, { attributes: true, attributeFilter: ['class'] });
    update();
  } catch (e) {
    try { var s = document.getElementById('planner'); if (s) { s.classList.add('pl-off'); s.removeAttribute('data-step'); } } catch (_) {}
  }
})();

/* scenes/widgets */
(function () {
  try {
    var sec = document.getElementById('widgets');
    if (!sec) return;
    var root = document.documentElement;
    var stage = sec.querySelector('.wg-stage');
    var head = sec.querySelector('.wg-head');
    var caps = sec.querySelector('.wg-caps');
    var world = sec.querySelector('.wg-world');
    var step = 0, measured = false, last = -1;
    function c01(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function seg(p, a, b) { return c01((p - a) / (b - a)); }
    function ease(t) { return t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2; }
    function out(t) { return 1 - Math.pow(1 - t, 3); }
    function set(k, v) { sec.style.setProperty(k, typeof v === 'number' ? v.toFixed(4) : v); }
    var KEYS = ['--in', '--w1', '--w2', '--w3', '--w4', '--zoom', '--dots', '--lock', '--a1', '--a2', '--world-top', '--world-h', '--dev-px', '--zoom-s', '--lift-y', '--dev-dy', '--dev-mask', '--hout', '--head-top', '--caps-top'];

    function measure() {
      var vw = window.innerWidth, vh = window.innerHeight, phone = vw < 900, wide = vw >= 1100;
      var top, h, ww;
      if (wide) {
        var hh = head.offsetHeight, ch = caps.offsetHeight;
        var ht = Math.max(84, (vh - hh - ch - 28) / 2);
        set('--head-top', ht + 'px');
        set('--caps-top', (ht + hh + 28) + 'px');
        top = 76; h = vh - top - 30;
        ww = world.offsetWidth || vw * .6;
      } else {
        top = head.offsetTop + head.offsetHeight + (phone ? 16 : 24);
        h = Math.max(240, vh - caps.offsetHeight - Math.max(22, vh * .032) - (phone ? 14 : 22) - top);
        ww = vw;
      }
      set('--world-top', top + 'px');
      set('--world-h', h + 'px');
      // The phone fills the height it is given (screen + bezel = 2.238 x its width).
      // On a phone it is allowed to run on under the words and fade out, like a crop.
      var dw = Math.min(h * .95 / 2.238, ww * .8, 420), dy = 0, mask = 'none';
      if (phone) {
        dw = Math.min(vw * .74, 340);
        var dh = dw * 2.238;
        if (dh > h) {
          dy = (dh - h) / 2;
          var room = vh - caps.offsetHeight - 30 - top;
          var cut = Math.max(0, Math.min(dh, room + 10));
          mask = 'linear-gradient(to bottom, #000 ' + Math.round(cut - 120) + 'px, transparent ' + Math.round(cut) + 'px)';
        }
      }
      set('--dev-px', Math.max(150, dw) + 'px');
      set('--dev-dy', dy + 'px');
      set('--dev-mask', mask);
      // Close-up: This morning grows to most of the room's width.
      var zs = Math.min(Math.min(ww * .86, wide ? 560 : 500) / (dw * 349 / 393), 2.2) - 1;
      set('--zoom-s', Math.max(.12, zs));
      // Move This morning's centre (10.9% of the screen height above its middle) to the room's middle.
      set('--lift-y', (dw * 852 / 393 * .109 - dy) + 'px');
      measured = true;
    }
    function clear() {
      KEYS.forEach(function (k) { sec.style.removeProperty(k); });
      sec.removeAttribute('data-step'); sec.classList.remove('wg-lifted');
      step = 0; measured = false; last = -1;
    }
    function update() {

      if (!root.classList.contains('motion')) { if (step) clear(); return; }
      if (!measured) measure();
      var p = film;
      if (Math.abs(p - last) < .0004 && step) return;
      last = p;
      set('--in', out(seg(p, 0, .12)));
      set('--w1', out(seg(p, .1, .19)));
      set('--w2', out(seg(p, .15, .24)));
      set('--w3', out(seg(p, .2, .29)));
      set('--w4', out(seg(p, .25, .34)));
      var z = ease(seg(p, .38, .5)) * (1 - ease(seg(p, .58, .68)));
      set('--zoom', z);
      sec.classList.toggle('wg-lifted', z > .001);
      // The dots start at the middle of the band and settle on the night's reading.
      set('--dots', p < .38 ? 1 : out(seg(p, .44, .56)));
      set('--hout', ease(seg(p, .63, .7)));
      set('--lock', ease(seg(p, .66, .75)));
      set('--a1', out(seg(p, .74, .82)));
      set('--a2', out(seg(p, .78, .86)));
      var s = p < .37 ? 1 : p < .63 ? 2 : 3;
      if (s !== step) { step = s; sec.setAttribute('data-step', String(s)); }
    }
    // A film: it plays once when the stage is half in view and holds its last frame.
    var D = 7200, film = 0, t0 = 0, raf = 0;
    var again = sec.querySelector('.wg-again');
    function tick(now) {
      raf = 0;
      if (!root.classList.contains('motion')) { film = 0; t0 = 0; update(); return; }
      film = c01((now - t0) / D);
      update();
      if (film < 1) raf = requestAnimationFrame(tick);
      else sec.classList.add('wg-done');
    }
    function play() {
      if (raf) cancelAnimationFrame(raf);
      sec.classList.remove('wg-done');
      film = 0; last = -1; t0 = performance.now();
      raf = requestAnimationFrame(tick);
    }
    if (again) again.addEventListener('click', play);
    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (es) {
        if (!t0 && es[0].intersectionRatio >= .5 && root.classList.contains('motion')) play();
      }, { threshold: [0, .5] }).observe(stage);
    } else { film = 1; }
    window.addEventListener('resize', function () { measured = false; last = -1; if (!raf) update(); }, { passive: true });
    new MutationObserver(function () { measured = false; last = -1; if (!root.classList.contains('motion')) { t0 = 0; film = 0; } update(); }).observe(root, { attributes: true, attributeFilter: ['class'] });
    update();
  } catch (e) {
    try { var s = document.getElementById('widgets'); if (s) { s.classList.add('wg-off'); s.removeAttribute('data-step'); } } catch (_) {}
  }
})();
