/* Generated by scripts/build_home.py from each scenes/NAME/scene.js. Edit those. */
/* scenes/engine */
(function () {
  try {
    var sec = document.getElementById('engine');
    if (!sec) return;
    var root = document.documentElement;
    var pin = sec.querySelector('.eng-pin');
    var stage = sec.querySelector('.eng-stage');
    var head = sec.querySelector('.eng-head');
    var word = sec.querySelector('.eng-word');
    var orb = sec.querySelector('.eng-orb .core');
    var img = sec.querySelector('.eng-device img');
    var flip = sec.getAttribute('data-flip') === '1';
    var ticking = false, near = false, step = 0, isWord = false, wordW = 0, wordH = 0, headBottom = 0;
    // Where "Good to go" sits on the 400 x 870 capture: centre and width.
    var TX = 144 / 400, TY = 284 / 870, TW = 248 / 400;
    function c01(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function seg(p, a, b) { return c01((p - a) / (b - a)); }
    function ease(t) { return t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2; }
    function set(k, v) { sec.style.setProperty(k, typeof v === 'number' ? v.toFixed(4) : v); }
    function measure() {
      wordW = word.offsetWidth; wordH = word.offsetHeight;
      head.style.transform = 'none';
      headBottom = head.offsetTop + head.offsetHeight;
      head.style.transform = '';
      set('--dev-top', (headBottom + 18) + 'px');
      var vh0 = window.innerHeight, vw0 = window.innerWidth;
      var room = vh0 - headBottom - 18 - (vw0 < 900 ? 44 : 28);
      set('--dev-w', Math.max(150, Math.min(vw0 * .66, 360, room / 2.2)) + 'px');
      var caps = sec.querySelector('.eng-caps');
      var capsTop = vh0 - (caps ? caps.offsetHeight : 90) - Math.max(22, vh0 * .03);
      var avail = capsTop - headBottom - 28;
      var bw = Math.max(240, Math.min(vw0 - 32, 600, (avail - 44) / 1.05 + 44));
      set('--board-w', bw + 'px');
      set('--board-y', ((headBottom + capsTop) / 2) + 'px');
    }
    function clear() {
      ['--a', '--b', '--c', '--d', '--hy', '--rise', '--fade', '--dev', '--bx', '--by', '--bs', '--bo', '--sweep', '--mk', '--dev-top', '--dev-w', '--board-w', '--board-y'].forEach(function (k) { sec.style.removeProperty(k); });
      sec.removeAttribute('data-step'); sec.classList.remove('is-word', 'is-landed');
      word.style.transform = ''; word.style.opacity = '';
      step = 0; isWord = false;
    }
    function update() {
      ticking = false;
      if (!root.classList.contains('motion')) { if (step) clear(); return; }
      if (!wordW) measure();
      var r = pin.getBoundingClientRect(), vh = window.innerHeight;
      var span = r.height - vh;
      var p = span > 0 ? c01(-r.top / span) : 1;
      set('--hy', 1 - ease(seg(p, 0, .16)));
      set('--rise', ease(seg(p, .03, .2)));
      set('--a', seg(p, .12, .32));
      set('--b', seg(p, .27, .42));
      set('--c', seg(p, .4, .54));
      set('--d', seg(p, .5, .58));
      set('--fade', ease(seg(p, .56, .68)));
      var dev = ease(seg(p, .7, .86));
      set('--dev', dev);
      var s = p < .27 ? 1 : p < .46 ? 2 : p < .74 ? 3 : 4;
      if (s !== step) { step = s; sec.setAttribute('data-step', String(s)); }
      var w = p > .55;
      if (w !== isWord) { isWord = w; sec.classList.toggle('is-word', w); }
      sec.classList.toggle('is-landed', p > .88);

      var st = stage.getBoundingClientRect();
      // Bloom: a burst of light where the three streams meet.
      var bl = seg(p, .55, .78);
      if (bl > 0 && bl < 1 && orb) {
        var o = orb.getBoundingClientRect();
        set('--bx', (o.left + o.width / 2 - st.left) + 'px');
        set('--by', (o.top + o.height / 2 - st.top) + 'px');
      }
      set('--bs', bl <= 0 ? 0 : .05 + Math.sin(Math.min(bl, 1) * Math.PI * .5) * 2.4);
      set('--bo', bl <= 0 || bl >= 1 ? 0 : Math.sin(bl * Math.PI) * .9);

      // The word: appears big in the middle, then lands on the real screen.
      var wa = ease(seg(p, .6, .7));
      set('--sweep', seg(p, .62, .78));
      var cx = st.width / 2, cy = st.height * .52;
      var k = ease(seg(p, .74, .9));
      var s0 = .82 + .18 * wa, x = cx, y = cy, sc = s0, op = wa;
      if (k > 0 && img) {
        var ir = img.getBoundingClientRect();
        if (flip) {
          var tx = ir.left - st.left + ir.width * TX, ty = ir.top - st.top + ir.height * TY;
          var ts = (ir.width * TW) / wordW;
          x = cx + (tx - cx) * k; y = cy + (ty - cy) * k; sc = s0 + (ts - s0) * k;
          op = wa * (1 - seg(p, .9, .95));
        } else {
          y = cy - k * st.height * .08; sc = s0 * (1 - .3 * k); op = wa * (1 - k);
        }
      }
      set('--mk', 1 - seg(p, .895, .93));
      word.style.opacity = op.toFixed(3);
      word.style.transform = 'translate3d(' + (x - wordW * sc / 2).toFixed(1) + 'px,' + (y - wordH * sc / 2).toFixed(1) + 'px,0) scale(' + sc.toFixed(4) + ')';
    }
    function onScroll() { if (near && !ticking) { ticking = true; requestAnimationFrame(update); } }
    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (es) { near = es[0].isIntersecting; if (near) onScroll(); }, { rootMargin: '50% 0px' }).observe(sec);
    } else { near = true; }
    window.addEventListener('scroll', onScroll, { passive: true });
    window.addEventListener('resize', function () { wordW = 0; onScroll(); }, { passive: true });
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(function () { wordW = 0; onScroll(); });
    update();
  } catch (e) {
    try { var s2 = document.getElementById('engine'); s2.removeAttribute('style'); s2.classList.add('eng-off'); } catch (e2) {}
  }
})();

/* scenes/planner */
/* Route planner scene: one scroll-scrubbed timeline through the pinned stage.
   Beat 1 (0 to .46): taps, the line follows the paths to each tap, distance counts.
   Beat 2 (.46 to .64): what you will meet pops up along the line.
   Beat 3 (.64 to 1): the map tilts away, the phone and the watch rise, the arrow turns.
   Without .motion, or on any error, the markup's final frame stays. */
(function () {
  try {
    var sec = document.getElementById('planner');
    if (!sec) return;
    var root = document.documentElement;
    var run = sec.querySelector('.pl-run');
    var paths = ['planner-route', 'planner-case', 'planner-glow'].map(function (id) { return document.getElementById(id); });
    var route = paths[0];
    var head = document.getElementById('planner-head');
    var comet = document.getElementById('planner-comet');
    var pins = [].slice.call(sec.querySelectorAll('.pl-pin'));
    var finger = document.getElementById('planner-finger');
    var rips = [].slice.call(sec.querySelectorAll('.pl-rip'));
    var dots = [].slice.call(sec.querySelectorAll('.pl-wp'));
    var guides = [].slice.call(sec.querySelectorAll('.pl-g'));
    var says = [].slice.call(sec.querySelectorAll('.pl-say'));
    var beats = [].slice.call(sec.querySelectorAll('.pl-rail li'));
    var num = sec.querySelector('.pl-num');
    if (!run || !route || !num) return;

    var KM = parseFloat(num.getAttribute('data-km')) || 6.4;
    var finalText = num.textContent;
    var lang = (root.getAttribute('lang') || 'en').slice(0, 2);
    var nf;
    try { nf = new Intl.NumberFormat(lang, { minimumFractionDigits: 1, maximumFractionDigits: 1 }); }
    catch (e) { nf = { format: function (v) { return v.toFixed(1); } }; }

    var L = route.getTotalLength();
    var wp = rips.map(function (c) { return { x: +c.getAttribute('cx'), y: +c.getAttribute('cy') }; });
    // Where each tap sits along the line, by nearest sample.
    function near(px, py) {
      var best = 0, bd = Infinity;
      for (var i = 0; i <= 500; i++) {
        var q = route.getPointAtLength(L * i / 500);
        var d = (q.x - px) * (q.x - px) + (q.y - py) * (q.y - py);
        if (d < bd) { bd = d; best = i / 500; }
      }
      return best;
    }
    var fr = wp.map(function (p) { return near(p.x, p.y); });
    fr[0] = 0; fr[fr.length - 1] = 1;
    // Pins pop as the light travelling along the line reaches them.
    var pf = pins.map(function (el) {
      var x = parseFloat(el.style.left) * 6, y = parseFloat(el.style.top) * 6.4;
      return near(x, y);
    });

    function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function out(v) { return 1 - Math.pow(1 - v, 3); }
    function inOut(v) { return v < 0.5 ? 4 * v * v * v : 1 - Math.pow(-2 * v + 2, 3) / 2; }
    function back(v) { if (v <= 0) return 0; if (v >= 1) return 1; var c = 1.7, c3 = c + 1; return 1 + c3 * Math.pow(v - 1, 3) + c * Math.pow(v - 1, 2); }
    function set(k, v) { sec.style.setProperty(k, v.toFixed(4)); }

    var VARS = ['--k', '--w', '--ph', '--turn', '--p0', '--p1', '--p2', '--b1', '--b2', '--b3'];
    var dead = false, live = false, shown = 0, target = 0, lastText = '', lastBeat = -1, buzz = false;

    function reset() {
      VARS.forEach(function (k) { sec.style.removeProperty(k); });
      paths.forEach(function (p) { if (p) { p.style.strokeDasharray = ''; p.style.strokeDashoffset = ''; } });
      [head, finger, comet].concat(rips, dots, guides).forEach(function (el) { if (el) el.removeAttribute('style'); });
      num.textContent = finalText;
      says.forEach(function (s, i) { s.classList.toggle('on', i === 0); });
      sec.classList.remove('pl-buzz');
      live = false; lastText = ''; lastBeat = -1;
    }

    function paint(t) {
      // Beat 1: the first tap, then three segments, each: finger travels, tap, line follows the paths.
      var d = 0, fx = wp[0].x, fy = wp[0].y;
      var fo = clamp(t / 0.04) * (1 - clamp((t - 0.46) / 0.04));
      var rip = [clamp((t - 0.035) / 0.06)];
      var gd = [];
      for (var j = 0; j < 3; j++) {
        var s = clamp((t - (0.08 + j * 0.125)) / 0.125);
        var m = inOut(clamp(s / 0.24));
        if (s > 0) { fx = wp[j].x + (wp[j + 1].x - wp[j].x) * m; fy = wp[j].y + (wp[j + 1].y - wp[j].y) * m; }
        rip.push(clamp((s - 0.2) / 0.28));
        gd.push(clamp((s - 0.18) / 0.08) * (1 - clamp((s - 0.86) / 0.14)));
        if (s > 0.3) d = fr[j] + (fr[j + 1] - fr[j]) * inOut(clamp((s - 0.3) / 0.7));
      }
      var dash = (L * (1 - d)).toFixed(1);
      paths.forEach(function (p) { if (p) { p.style.strokeDasharray = L.toFixed(1) + ' ' + (L + 2).toFixed(1); p.style.strokeDashoffset = dash; } });
      if (head) {
        var hp = route.getPointAtLength(L * d);
        head.setAttribute('cx', hp.x.toFixed(1));
        head.setAttribute('cy', hp.y.toFixed(1));
        head.style.opacity = d > 0.002 && t < 0.47 ? 1 : 0;
      }
      if (finger) {
        finger.setAttribute('transform', 'translate(' + fx.toFixed(1) + ' ' + fy.toFixed(1) + ')');
        finger.style.opacity = fo.toFixed(3);
      }
      rips.forEach(function (c, i) {
        var r = rip[i] || 0;
        c.setAttribute('r', (6 + r * 24).toFixed(1));
        c.style.opacity = r > 0 && r < 1 ? (1 - r).toFixed(3) : 0;
        if (dots[i]) dots[i].style.opacity = clamp(r * 4).toFixed(3);
      });
      guides.forEach(function (g, i) { g.style.opacity = (gd[i] * 0.85).toFixed(3); });
      var text = nf.format(Math.round(KM * d * 10) / 10);
      if (text !== lastText) { num.textContent = text; lastText = text; }

      // Beat 2: what you will meet.
      var c = clamp((t - 0.465) / 0.15);
      if (comet) {
        var cp = route.getPointAtLength(L * c);
        comet.setAttribute('cx', cp.x.toFixed(1));
        comet.setAttribute('cy', cp.y.toFixed(1));
        comet.style.opacity = (clamp(c * 12) * (1 - clamp((c - 0.97) / 0.03))).toFixed(3);
      }
      pf.forEach(function (f, i) {
        var at = 0.465 + 0.15 * f - 0.01;
        set('--p' + i, back(clamp((t - at) / 0.06)));
      });

      // Beat 3: to your wrist.
      set('--k', inOut(clamp((t - 0.64) / 0.22)));
      set('--ph', out(clamp((t - 0.68) / 0.16)));
      set('--w', out(clamp((t - 0.72) / 0.16)));
      set('--turn', inOut(clamp((t - 0.87) / 0.08)));
      var bz = t > 0.93;
      if (bz !== buzz) { buzz = bz; sec.classList.toggle('pl-buzz', bz); }

      set('--b1', clamp(t / 0.46));
      set('--b2', clamp((t - 0.46) / 0.18));
      set('--b3', clamp((t - 0.64) / 0.31));
      var beat = t < 0.46 ? 0 : t < 0.64 ? 1 : 2;
      if (beat !== lastBeat) {
        lastBeat = beat;
        says.forEach(function (s, i) { s.classList.toggle('on', i === beat); });
        beats.forEach(function (s, i) { s.classList.toggle('on', i === beat); });
      }
    }

    function progress() {
      var r = run.getBoundingClientRect();
      var vh = window.innerHeight;
      var span = r.height - vh;
      if (span < 10) return 1;
      return clamp(-r.top / span);
    }

    var ticking = false, easing = false;
    function step() {
      easing = false;
      try {
        if (!root.classList.contains('motion')) { if (live) reset(); return; }
        var delta = target - shown;
        shown = Math.abs(delta) < 0.0008 ? target : shown + delta * 0.16;
        live = true;
        paint(shown);
        if (shown !== target) { easing = true; requestAnimationFrame(step); }
      } catch (e) { dead = true; reset(); }
    }
    function frame() {
      ticking = false;
      if (dead) return;
      try {
        if (!root.classList.contains('motion')) { if (live) reset(); return; }
        var r = run.getBoundingClientRect(), vh = window.innerHeight;
        if (r.bottom < -vh * 0.3 || r.top > vh * 1.3) return;   // far away: rest
        target = progress();
        if (!live) shown = target;
        if (!easing) { easing = true; requestAnimationFrame(step); }
      } catch (e) { dead = true; reset(); }
    }
    function request() {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(frame);
    }
    window.addEventListener('scroll', request, { passive: true });
    window.addEventListener('resize', request, { passive: true });
    window.addEventListener('load', request);
    request();
  } catch (e) { /* the final frame in the markup stays */ }
})();

/* scenes/widgets */
/* Widgets scene: scroll through the pin and the Home Screen straightens, the
   widgets fly in from depth one by one, then it dims to the Lock Screen.
   Writes custom properties only; CSS turns them into transforms. */
(function () {
  try {
    var root = document.documentElement;
    var sec = document.querySelector('.scene-widgets');
    if (!sec) return;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    var pin = sec.querySelector('.wg-pin');
    var beats = [].slice.call(sec.querySelectorAll('.wg-beats li'));
    var watch = sec.querySelector('.wg-watch');
    var nums = [].slice.call(sec.querySelectorAll('.wg-num'));
    if (!pin) return;

    function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function seg(t, a, b) { return clamp((t - a) / (b - a)); }
    function out3(x) { return 1 - Math.pow(1 - x, 3); }
    function inOut(x) { return x < 0.5 ? 4 * x * x * x : 1 - Math.pow(-2 * x + 2, 3) / 2; }
    function back(x) { var c1 = 1.5, c3 = c1 + 1; return x <= 0 ? 0 : x >= 1 ? 1 : 1 + c3 * Math.pow(x - 1, 3) + c1 * Math.pow(x - 1, 2); }

    var last = {}, lastBeat = -1, lastWatch = null, lastNum = -1;
    function set(k, v) {
      var s = v.toFixed(4);
      if (last[k] === s) return;
      last[k] = s;
      sec.style.setProperty(k, s);
    }

    // Widget windows along the pin: [start, end].
    var W = [[0.06, 0.26], [0.13, 0.33], [0.22, 0.44], [0.31, 0.53]];

    function paint(t) {
      var a = inOut(seg(t, 0, 0.52));
      set('--tilt', 1 - a);
      set('--sh', Math.sin(Math.PI * seg(t, 0.12, 0.6)));
      for (var i = 0; i < 4; i++) {
        var p = seg(t, W[i][0], W[i][1]);
        set('--w' + (i + 1), back(p));
        set('--o' + (i + 1), clamp(p * 2.6));
      }
      var f1 = out3(seg(t, 0.2, 0.36));
      set('--f1', f1);
      set('--f3', out3(seg(t, 0.36, 0.52)));
      set('--f4', out3(seg(t, 0.45, 0.62)));
      set('--lk', inOut(seg(t, 0.62, 0.71)));
      set('--lc', out3(seg(t, 0.67, 0.79)));
      set('--l1', back(seg(t, 0.72, 0.84)));
      set('--l2', back(seg(t, 0.77, 0.89)));

      var n = Math.round(84 * f1);
      if (n !== lastNum) {
        lastNum = n;
        nums.forEach(function (el) { el.textContent = String(n); });
      }
      var b = t < 0.62 ? 0 : t < 0.9 ? 1 : 2;
      if (b !== lastBeat) {
        lastBeat = b;
        beats.forEach(function (li, j) { li.classList.toggle('on', j === b); });
      }
      var w = t > 0.88;
      if (w !== lastWatch && watch) { lastWatch = w; watch.classList.toggle('on', w); }
    }

    var ticking = false;
    function frame() {
      ticking = false;
      try {
        if (!root.classList.contains('motion')) { stop(); return; }
        var vh = window.innerHeight;
        var r = pin.getBoundingClientRect();
        if (r.bottom < -vh * 0.5 || r.top > vh * 1.5) return;
        var span = r.height - vh;
        var t = span > 0 ? clamp(-r.top / span) : 1;
        paint(t);
      } catch (e) { stop(); }
    }
    function request() {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(frame);
    }
    function stop() {
      sec.classList.remove('wg-live');
      ['--tilt', '--sh', '--w1', '--w2', '--w3', '--w4', '--o1', '--o2', '--o3', '--o4', '--f1', '--f3', '--f4', '--lk', '--lc', '--l1', '--l2']
        .forEach(function (k) { sec.style.removeProperty(k); });
      nums.forEach(function (el) { el.textContent = el.getAttribute('data-to'); });
      beats.forEach(function (li, j) { li.classList.toggle('on', j === 0); });
      window.removeEventListener('scroll', request);
      window.removeEventListener('resize', request);
    }

    // home.js adds .motion; wait for it if this file runs first.
    var started = false;
    function boot() {
      if (started || !root.classList.contains('motion')) return;
      started = true;
      paint(0);
      sec.classList.add('wg-live');
      window.addEventListener('scroll', request, { passive: true });
      window.addEventListener('resize', request, { passive: true });
      request();
    }
    boot();
    document.addEventListener('DOMContentLoaded', boot);
    window.addEventListener('load', function () { boot(); if (started) request(); });
  } catch (e) {
    try {
      var s = document.querySelector('.scene-widgets');
      if (s) {
        s.classList.remove('wg-live');
        [].slice.call(s.querySelectorAll('.wg-num')).forEach(function (el) { el.textContent = el.getAttribute('data-to'); });
      }
    } catch (e2) { /* static state stays */ }
  }
})();
