/* Generated by scripts/build_home.py from each scenes/NAME/scene.js. Edit those. */
/* scenes/engine */
(function () {
  try {
    var sec = document.getElementById('engine');
    if (!sec) return;
    var root = document.documentElement;
        var stage = sec.querySelector('.eng-stage');
    var head = sec.querySelector('.eng-head');
    var word = sec.querySelector('.eng-word');
    var orb = sec.querySelector('.eng-orb .core');
    var img = sec.querySelector('.eng-device img');
    var flip = sec.getAttribute('data-flip') === '1';
    var ticking = false, step = 0, isWord = false, wordW = 0, wordH = 0, headBottom = 0;
    // Plays once, like a film, when the stage is half in view, then holds on the last frame.
    var DUR = 7000, t0 = 0, done = false;
    // Where "Good to go" sits on the 400 x 870 capture: centre and width.
    var TX = 144 / 400, TY = 284 / 870, TW = 248 / 400;
    function c01(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function seg(p, a, b) { return c01((p - a) / (b - a)); }
    function ease(t) { return t < .5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2; }
    function set(k, v) { sec.style.setProperty(k, typeof v === 'number' ? v.toFixed(4) : v); }
    // Geometry for the film, read once (and on resize) so no frame ever forces a layout.
    // G.dev*: the phone at rest; G.img*: the capture inside it; G.orb*: the orb relative
    // to the board's centre at full size. Frames map these through the current transforms.
    var G = null;
    function measure() {
      wordW = word.offsetWidth; wordH = word.offsetHeight;
      head.style.transform = 'none';
      headBottom = head.offsetTop + head.offsetHeight;
      head.style.transform = '';
      set('--dev-top', (headBottom + 18) + 'px');
      var vh0 = stage.clientHeight || window.innerHeight, vw0 = window.innerWidth;
      var room = vh0 - headBottom - 18 - (vw0 < 900 ? 44 : 28);
      set('--dev-w', Math.max(150, Math.min(vw0 * .66, 360, room / 2.2)) + 'px');
      var caps = sec.querySelector('.eng-caps');
      var capsTop = vh0 - (caps ? caps.offsetHeight : 90) - Math.max(22, vh0 * .03);
      var avail = capsTop - headBottom - 28;
      var bw = Math.max(240, Math.min(vw0 - 32, 600, (avail - 44) / 1.05 + 44));
      set('--board-w', bw + 'px');
      set('--board-y', ((headBottom + capsTop) / 2) + 'px');
      // Read the resting frame: board risen, nothing faded, phone in place.
      var keep = ['--rise', '--fade', '--dev'].map(function (k) { return sec.style.getPropertyValue(k); });
      sec.style.setProperty('--rise', '1'); sec.style.setProperty('--fade', '0'); sec.style.setProperty('--dev', '1');
      var st = stage.getBoundingClientRect(), dev = sec.querySelector('.eng-device').getBoundingClientRect();
      var bd = sec.querySelector('.eng-board').getBoundingClientRect();
      var ir = img ? img.getBoundingClientRect() : dev, o = orb ? orb.getBoundingClientRect() : bd;
      G = {
        w: st.width, h: st.height,
        dcx: dev.left - st.left + dev.width / 2, dcy: dev.top - st.top + dev.height / 2,
        tx: ir.left - st.left + ir.width * TX, ty: ir.top - st.top + ir.height * TY, tw: ir.width * TW,
        bcx: bd.left - st.left + bd.width / 2, bcy: bd.top - st.top + bd.height / 2,
        ox: o.left + o.width / 2 - (bd.left + bd.width / 2), oy: o.top + o.height / 2 - (bd.top + bd.height / 2)
      };
      ['--rise', '--fade', '--dev'].forEach(function (k, i) { if (keep[i]) sec.style.setProperty(k, keep[i]); else sec.style.removeProperty(k); });
    }
    function clear() {
      ['--a', '--b', '--c', '--d', '--hy', '--rise', '--fade', '--dev', '--bx', '--by', '--bs', '--bo', '--glow', '--mk', '--dev-top', '--dev-w', '--board-w', '--board-y'].forEach(function (k) { sec.style.removeProperty(k); });
      sec.removeAttribute('data-step'); sec.classList.remove('is-word', 'is-landed');
      word.style.transform = ''; word.style.opacity = '';
      step = 0; isWord = false;
    }
    function update() {
      ticking = false;
      if (!root.classList.contains('motion')) { if (step) clear(); return; }
      if (!wordW || !G) measure();
      var p = done ? 1 : t0 ? c01((performance.now() - t0) / DUR) : 0;
      if (p >= 1) done = true;
      set('--hy', 1 - ease(seg(p, 0, .16)));
      set('--rise', ease(seg(p, .03, .2)));
      set('--a', seg(p, .12, .32));
      set('--b', seg(p, .27, .42));
      set('--c', seg(p, .4, .54));
      set('--d', seg(p, .5, .58));
      set('--fade', ease(seg(p, .56, .68)));
      var dev = ease(seg(p, .7, .86));
      set('--dev', dev);
      var s = p < .27 ? 1 : p < .46 ? 2 : p < .74 ? 3 : 4;
      if (s !== step) { step = s; sec.setAttribute('data-step', String(s)); }
      var w = p > .55;
      if (w !== isWord) { isWord = w; sec.classList.toggle('is-word', w); }
      sec.classList.toggle('is-landed', p > .88);

      // Bloom: a burst of light where the three streams meet.
      var bl = seg(p, .55, .78);
      if (bl > 0 && bl < 1) {
        var bsc = 1 - .14 * ease(seg(p, .56, .68));
        set('--bx', (G.bcx + G.ox * bsc) + 'px');
        set('--by', (G.bcy + G.oy * bsc) + 'px');
      }
      set('--bs', bl <= 0 ? 0 : .05 + Math.sin(Math.min(bl, 1) * Math.PI * .5) * 2.4);
      set('--bo', bl <= 0 || bl >= 1 ? 0 : Math.sin(bl * Math.PI) * .9);

      // The word: appears big in the middle, then lands on the real screen.
      var wa = ease(seg(p, .6, .7));
      set('--glow', Math.sin(seg(p, .62, .82) * Math.PI));
      var cx = G.w / 2, cy = G.h * .52;
      var k = ease(seg(p, .74, .9));
      var s0 = .82 + .18 * wa, x = cx, y = cy, sc = s0, op = wa;
      if (k > 0) {
        if (flip) {
          // Where "Good to go" sits on the capture right now: the resting spot mapped
          // through the phone's current rise and scale (about its own centre).
          var ds = .9 + dev * .1, dy = (1 - dev) * .7 * G.h;
          var tx = G.dcx + (G.tx - G.dcx) * ds, ty = G.dcy + (G.ty - G.dcy) * ds + dy;
          var ts = (G.tw * ds) / wordW;
          x = cx + (tx - cx) * k; y = cy + (ty - cy) * k; sc = s0 + (ts - s0) * k;
          op = wa * (1 - seg(p, .9, .95));
        } else {
          y = cy - k * G.h * .08; sc = s0 * (1 - .3 * k); op = wa * (1 - k);
        }
      }
      set('--mk', 1 - seg(p, .895, .93));
      word.style.opacity = op.toFixed(3);
      word.style.transform = 'translate3d(' + (x - wordW * sc / 2).toFixed(1) + 'px,' + (y - wordH * sc / 2).toFixed(1) + 'px,0) scale(' + sc.toFixed(4) + ')';
    }
    function frame() { update(); if (t0 && !done) requestAnimationFrame(frame); }
    function play() { if (t0 || done) return; t0 = performance.now(); requestAnimationFrame(frame); }
    function redraw() { if (!ticking) { ticking = true; requestAnimationFrame(update); } }
    if ('IntersectionObserver' in window) {
      new IntersectionObserver(function (es) { if (es[0].isIntersecting) play(); }, { threshold: .5 }).observe(stage);
    } else { done = true; }
    window.addEventListener('resize', function () { wordW = 0; redraw(); }, { passive: true });
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(function () { wordW = 0; redraw(); });
    update();
  } catch (e) {
    try { var s2 = document.getElementById('engine'); s2.removeAttribute('style'); s2.classList.add('eng-off'); } catch (e2) {}
  }
})();

/* scenes/flyover */
/* Flyover scene: scroll flies a camera over the contour model. The route draws
   with the runner on its head, the camera follows it, eases to a stop at the
   fastest split and at the top of the climb, then pulls back up and away while
   the real capture rises in. Only transforms and opacity change per frame.
   Without .motion the CSS defaults are the finished frame; this file then only
   pins the runner and the two callouts to it. On any error it steps aside. */
(function () {
  var sec = document.getElementById('flyover');
  if (!sec) return;
  var root = document.documentElement;
  var stage, pin, cam, world, puck, copy, chips, layers, nums, routeEl;
  var PX = [], PY = [], HD = [], Z, E, PACE, HR, pS, pC, NS = 300;
  var cfg = {}, alive = true, ticking = false, mode = '', copyIn = false, saved = [];

  function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
  function ss(a, b, x) { x = clamp((x - a) / (b - a)); return x * x * (3 - 2 * x); }
  function lerp(a, b, k) { return a + (b - a) * k; }
  function bump(a, m, b, x) { return x < m ? ss(a, m, x) : 1 - ss(m, b, x); }
  function sample(arr, p) {
    var f = clamp(p) * (arr.length - 1), i = Math.floor(f), k = f - i;
    return i >= arr.length - 1 ? arr[arr.length - 1] : arr[i] + (arr[i + 1] - arr[i]) * k;
  }
  function list(name) { return (sec.getAttribute('data-' + name) || '0').split(',').map(Number); }
  function num(cs, name, fallback) { var v = parseFloat(cs.getPropertyValue(name)); return isNaN(v) ? fallback : v; }
  function mmss(s) { s = Math.round(s); var m = Math.floor(s / 60), r = s % 60; return m + ':' + (r < 10 ? '0' : '') + r; }
  function put(el, name, v) { el.style.setProperty(name, v); }

  function setup() {
    stage = sec.querySelector('.fo-stage');
    pin = sec.querySelector('.fo-pin');
    cam = sec.querySelector('.fo-cam');
    world = sec.querySelector('.fo-world');
    puck = sec.querySelector('.fo-puck');
    copy = sec.querySelector('.fo-copy');
    routeEl = document.getElementById('flyover-r');
    chips = [].slice.call(sec.querySelectorAll('.fo-chip'));
    layers = [].slice.call(sec.querySelectorAll('.fo-l[data-r]')).map(function (el) {
      var r = el.getAttribute('data-r').split(' ').map(Number);
      return { el: el, lo: r[0], hi: r[1], d: -1 };
    });
    nums = {};
    [].slice.call(sec.querySelectorAll('.fo-hud b[data-k]')).forEach(function (b) {
      nums[b.getAttribute('data-k')] = { el: b, v: b.textContent };
    });
    Z = list('z'); E = list('e'); PACE = list('pace'); HR = list('hr');
    pS = Number(sec.getAttribute('data-ps')) || 0.25;
    pC = Number(sec.getAttribute('data-pc')) || 0.7;

    var len = routeEl.getTotalLength(), ang = [], i, j;
    for (i = 0; i <= NS; i++) {
      var q = routeEl.getPointAtLength(len * i / NS);
      PX.push(q.x); PY.push(q.y);
    }
    for (i = 0; i < NS; i++) ang.push(Math.atan2(PY[i + 1] - PY[i], PX[i + 1] - PX[i]));
    ang.push(ang[NS - 1]);
    for (i = 1; i <= NS; i++) {            // unwrap
      while (ang[i] - ang[i - 1] > Math.PI) ang[i] -= 2 * Math.PI;
      while (ang[i] - ang[i - 1] < -Math.PI) ang[i] += 2 * Math.PI;
    }
    var sig = 26, w = [];                    // wide kernel: switchbacks average out
    for (j = -3 * sig; j <= 3 * sig; j++) w.push(Math.exp(-j * j / (2 * sig * sig)));
    for (i = 0; i <= NS; i++) {
      var s = 0, ws = 0;
      for (j = -3 * sig; j <= 3 * sig; j++) {
        var k = Math.min(NS, Math.max(0, i + j)), wt = w[j + 3 * sig];
        s += ang[k] * wt; ws += wt;
      }
      HD.push(-90 - (s / ws) * 180 / Math.PI);
    }
    [world, puck, stage].concat(chips, layers.map(function (l) { return l.el; })).forEach(function (el) {
      saved.push([el, el.getAttribute('style')]);
    });
  }

  function readConfig() {
    var cs = getComputedStyle(world), cs2 = getComputedStyle(sec), cc = getComputedStyle(cam);
    cfg.W = world.offsetWidth;
    cfg.u = cfg.W / 1000;
    cfg.dz = cfg.W * num(cs2, '--dzk', 0.018);
    cfg.oZm = num(cs2, '--o-zm', 0.86);
    cfg.fZm = num(cs2, '--f-zm', 1.8);
    cfg.fCy = num(cs2, '--f-cy', 0.15);
    cfg.eTilt = num(cs, '--e-tilt', 52);
    cfg.eHd = num(cs, '--e-hd', -18);
    cfg.eZm = num(cs, '--e-zm', 0.86);
    cfg.eFx = num(cs, '--e-fx', 520);
    cfg.eFy = num(cs, '--e-fy', 540);
    cfg.eCx = num(cs, '--e-cx', 0);
    cfg.eCy = num(cs, '--e-cy', 0.1);
    cfg.endChips = num(cs2, '--end-chips', 1);
    cfg.eCyPx = cfg.eCy * cfg.W;
    if (cfg.vw < 900 && copy.offsetHeight) {
      // Phones: fit the finished model into the space the copy leaves free.
      var below = copy.offsetTop + copy.offsetHeight, free = cfg.vh - below;
      var k = Math.min(1.2, Math.max(0.7, free / 454));
      cfg.eZm *= k;
      cfg.eCyPx = below + free * 0.6 - cfg.vh / 2;
      if (free < 400) cfg.endChips = 0;
    }
    cfg.eHdU = cfg.eHd + 360 * Math.round((HD[NS] - cfg.eHd) / 360);
    cfg.d = parseFloat(cc.perspective) || 1500;
    var po = cc.perspectiveOrigin.split(' ');
    cfg.vw = cam.clientWidth;
    cfg.vh = cam.clientHeight;
    cfg.pox = parseFloat(po[0]); if (isNaN(cfg.pox)) cfg.pox = cfg.vw / 2;
    cfg.poy = parseFloat(po[1]); if (isNaN(cfg.poy)) cfg.poy = cfg.vh / 2;
  }

  // Route progress: eases into a full stop at the split and at the summit.
  var K = null;
  function progress(t) {
    if (!K) K = [[0.08, 0], [0.24, pS], [0.31, pS], [0.58, pC], [0.66, pC], [0.79, 1]];
    if (t <= K[0][0]) return 0;
    for (var i = 1; i < K.length; i++) {
      if (t <= K[i][0]) return lerp(K[i - 1][1], K[i][1], ss(K[i - 1][0], K[i][0], t));
    }
    return 1;
  }

  // The camera for a moment t of the flight. pose(1) equals the CSS defaults.
  function pose(t) {
    var p = progress(t), pl = progress(t - 0.014);
    var dive = ss(0.02, 0.2, t), away = ss(0.74, 0.95, t);
    var atTop = bump(0.55, 0.62, 0.7, t), atSplit = bump(0.21, 0.275, 0.34, t);
    var hx = sample(PX, pl), hy = sample(PY, pl), hz = sample(Z, pl);
    var hd = lerp(HD[0] + 46 * (1 - ss(0, 0.2, t)), sample(HD, pl), dive);
    return {
      p: p,
      fx: lerp(lerp(515, hx, dive), cfg.eFx, away),
      fy: lerp(lerp(560, hy, dive), cfg.eFy, away),
      fz: lerp(hz * dive, 0, away),
      hd: lerp(hd, cfg.eHdU, away),
      zm: lerp(lerp(cfg.oZm, cfg.fZm, dive), cfg.eZm, away) * (1 - 0.2 * atTop) * (1 + 0.06 * atSplit),
      tilt: lerp(lerp(48, 62, dive) - 9 * atTop - 12 * ss(0.6, 0.7, t), cfg.eTilt, away),
      cx: cfg.eCx * cfg.W * away,
      cy: lerp((lerp(0.06, cfg.fCy, dive) - 0.1 * atTop) * cfg.vh, cfg.eCyPx, away)
    };
  }

  // Where a point of the model lands on the stage, the same chain the CSS uses.
  function project(c, xw, yw, lv) {
    var x = (xw - 500) * cfg.u + (500 - c.fx) * cfg.u;
    var y = (yw - 500) * cfg.u + (500 - c.fy) * cfg.u;
    var z = lv * cfg.dz - c.fz * cfg.dz;
    x *= c.zm; y *= c.zm; z *= c.zm;
    var a = c.hd * Math.PI / 180, ca = Math.cos(a), sa = Math.sin(a);
    var x1 = x * ca - y * sa, y1 = x * sa + y * ca;
    var b = c.tilt * Math.PI / 180, cb = Math.cos(b), sb = Math.sin(b);
    var y2 = y1 * cb - z * sb, z2 = y1 * sb + z * cb;
    var X = cfg.vw / 2 + x1 + c.cx, Y = cfg.vh / 2 + y2 + c.cy;
    var s = cfg.d / Math.max(cfg.d - z2, 1);
    return [cfg.pox + (X - cfg.pox) * s, cfg.poy + (Y - cfg.poy) * s];
  }

  function pinTo(el, c, xw, yw, lv) {
    var q = project(c, xw, yw, lv);
    put(el, '--sx', q[0].toFixed(1) + 'px');
    put(el, '--sy', q[1].toFixed(1) + 'px');
  }

  function pins(c, p) {
    pinTo(puck, c, sample(PX, p), sample(PY, p), sample(Z, p));
    pinTo(chips[0], c, sample(PX, pS), sample(PY, pS), sample(Z, pS));
    pinTo(chips[1], c, sample(PX, pC), sample(PY, pC), sample(Z, pC));
  }

  function applyWorld(c) {
    put(world, '--tilt', c.tilt.toFixed(2) + 'deg');
    put(world, '--hd', c.hd.toFixed(2) + 'deg');
    put(world, '--zm', c.zm.toFixed(4));
    put(world, '--px', ((500 - c.fx) * cfg.u).toFixed(1) + 'px');
    put(world, '--py', ((500 - c.fy) * cfg.u).toFixed(1) + 'px');
    put(world, '--pz', (-c.fz * cfg.dz).toFixed(1) + 'px');
    put(world, '--cx', c.cx.toFixed(1) + 'px');
    put(world, '--cy', c.cy.toFixed(1) + 'px');
  }

  function render(t) {
    var c = pose(t), p = c.p;
    applyWorld(c);
    pins(c, p);

    layers.forEach(function (l) {
      var d = 1 - Math.min(l.hi, Math.max(l.lo, p));
      if (Math.abs(d - l.d) > 0.0002) { l.d = d; put(l.el, '--d', d.toFixed(4)); }
    });

    var end1 = ss(0.86, 0.93, t) * cfg.endChips, end2 = ss(0.88, 0.95, t);
    put(chips[0], '--a', Math.max(ss(0.19, 0.235, t) * (1 - ss(0.35, 0.4, t)), end1).toFixed(3));
    put(chips[1], '--a', Math.max(ss(0.53, 0.575, t) * (1 - ss(0.69, 0.74, t)), end2).toFixed(3));

    put(puck, '--pa', (1 - ss(0.8, 0.88, t)).toFixed(3));
    put(stage, '--hud', (ss(0.015, 0.07, t) * (1 - ss(0.72, 0.78, t))).toFixed(3));
    put(stage, '--p', p.toFixed(4));
    put(stage, '--ct', Math.max(1 - ss(0.05, 0.13, t), ss(0.76, 0.88, t)).toFixed(3));
    put(stage, '--cp', ss(0.79, 0.91, t).toFixed(3));
    put(stage, '--pr', ss(0.78, 0.97, t).toFixed(4));
    var want = t < 0.09 || t > 0.75;
    if (want !== copyIn) { copyIn = want; copy.classList.toggle('in', want); }

    text('e', String(Math.round(sample(E, p))));
    text('pace', mmss(sample(PACE, p)));
    text('hr', String(Math.round(sample(HR, p))));
  }

  function text(k, v) {
    var n = nums[k];
    if (n && n.v !== v) { n.v = v; n.el.textContent = v; }
  }

  function reset() {
    saved.forEach(function (it) {
      if (it[1] === null) it[0].removeAttribute('style'); else it[0].setAttribute('style', it[1]);
    });
    layers.forEach(function (l) { l.d = -1; });
    copy.classList.add('in');
    copyIn = true;
  }

  function frame() {
    ticking = false;
    if (!alive) return;
    try {
      var moving = root.classList.contains('motion');
      if (!moving) {
        // The finished frame: only the runner and the callouts need placing.
        if (mode !== 'still') {
          reset(); mode = 'still'; readConfig();
          var c = pose(1); applyWorld(c); pins(c, 1);
          if (!cfg.endChips) put(chips[0], 'display', 'none');
        }
        return;
      }
      var r = pin.getBoundingClientRect(), vh = window.innerHeight;
      if (r.bottom < -200 || r.top > vh + 200) return;
      if (mode !== 'fly') { mode = 'fly'; readConfig(); copyIn = false; copy.classList.remove('in'); }
      var span = r.height - vh;
      render(span > 0 ? clamp(-r.top / span) : 1);
    } catch (e) {
      alive = false;
      try { reset(); sec.classList.remove('fo-js'); } catch (e2) { /* the static frame stays */ }
    }
  }
  function request() {
    if (ticking) return;
    ticking = true;
    requestAnimationFrame(frame);
    setTimeout(function () { if (ticking) frame(); }, 250);
  }

  try {
    setup();
    sec.classList.add('fo-js');
    window.addEventListener('scroll', request, { passive: true });
    window.addEventListener('resize', function () { mode = ''; request(); }, { passive: true });
    window.addEventListener('load', function () { mode = ''; request(); });
    request();
  } catch (e) {
    alive = false;
  }
})();

/* scenes/planner */
/* Route planner scene: one scroll-scrubbed timeline through the pinned stage.
   Beat 1 (0 to .46): taps, the line follows the paths to each tap, distance counts.
   Beat 2 (.46 to .64): what you will meet pops up along the line.
   Beat 3 (.64 to 1): the map tilts away, the phone and the watch rise, the arrow turns.
   Without .motion, or on any error, the markup's final frame stays. */
(function () {
  try {
    var sec = document.getElementById('planner');
    if (!sec) return;
    var root = document.documentElement;
    var run = sec.querySelector('.pl-run');
    var paths = ['planner-route', 'planner-case', 'planner-glow'].map(function (id) { return document.getElementById(id); });
    var route = paths[0];
    var head = document.getElementById('planner-head');
    var comet = document.getElementById('planner-comet');
    var pins = [].slice.call(sec.querySelectorAll('.pl-pin'));
    var finger = document.getElementById('planner-finger');
    var rips = [].slice.call(sec.querySelectorAll('.pl-rip'));
    var dots = [].slice.call(sec.querySelectorAll('.pl-wp'));
    var guides = [].slice.call(sec.querySelectorAll('.pl-g'));
    var says = [].slice.call(sec.querySelectorAll('.pl-say'));
    var beats = [].slice.call(sec.querySelectorAll('.pl-rail li'));
    var num = sec.querySelector('.pl-num');
    if (!run || !route || !num) return;

    var KM = parseFloat(num.getAttribute('data-km')) || 6.4;
    var finalText = num.textContent;
    var lang = (root.getAttribute('lang') || 'en').slice(0, 2);
    var nf;
    try { nf = new Intl.NumberFormat(lang, { minimumFractionDigits: 1, maximumFractionDigits: 1 }); }
    catch (e) { nf = { format: function (v) { return v.toFixed(1); } }; }

    var L = route.getTotalLength();
    var wp = rips.map(function (c) { return { x: +c.getAttribute('cx'), y: +c.getAttribute('cy') }; });
    // Where each tap sits along the line, by nearest sample.
    function near(px, py) {
      var best = 0, bd = Infinity;
      for (var i = 0; i <= 500; i++) {
        var q = route.getPointAtLength(L * i / 500);
        var d = (q.x - px) * (q.x - px) + (q.y - py) * (q.y - py);
        if (d < bd) { bd = d; best = i / 500; }
      }
      return best;
    }
    var fr = wp.map(function (p) { return near(p.x, p.y); });
    fr[0] = 0; fr[fr.length - 1] = 1;
    // Pins pop as the light travelling along the line reaches them.
    var pf = pins.map(function (el) {
      var x = parseFloat(el.style.left) * 6, y = parseFloat(el.style.top) * 6.4;
      return near(x, y);
    });

    function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function out(v) { return 1 - Math.pow(1 - v, 3); }
    function inOut(v) { return v < 0.5 ? 4 * v * v * v : 1 - Math.pow(-2 * v + 2, 3) / 2; }
    function back(v) { if (v <= 0) return 0; if (v >= 1) return 1; var c = 1.7, c3 = c + 1; return 1 + c3 * Math.pow(v - 1, 3) + c * Math.pow(v - 1, 2); }
    function set(k, v) { sec.style.setProperty(k, v.toFixed(4)); }

    var VARS = ['--k', '--w', '--ph', '--turn', '--p0', '--p1', '--p2', '--b1', '--b2', '--b3'];
    var dead = false, live = false, shown = 0, target = 0, lastText = '', lastBeat = -1, buzz = false;

    function reset() {
      VARS.forEach(function (k) { sec.style.removeProperty(k); });
      paths.forEach(function (p) { if (p) { p.style.strokeDasharray = ''; p.style.strokeDashoffset = ''; } });
      [head, finger, comet].concat(rips, dots, guides).forEach(function (el) { if (el) el.removeAttribute('style'); });
      num.textContent = finalText;
      says.forEach(function (s, i) { s.classList.toggle('on', i === 0); });
      sec.classList.remove('pl-buzz');
      live = false; lastText = ''; lastBeat = -1;
    }

    function paint(t) {
      // Beat 1: the first tap, then three segments, each: finger travels, tap, line follows the paths.
      var d = 0, fx = wp[0].x, fy = wp[0].y;
      var fo = clamp(t / 0.04) * (1 - clamp((t - 0.46) / 0.04));
      var rip = [clamp((t - 0.035) / 0.06)];
      var gd = [];
      for (var j = 0; j < 3; j++) {
        var s = clamp((t - (0.08 + j * 0.125)) / 0.125);
        var m = inOut(clamp(s / 0.24));
        if (s > 0) { fx = wp[j].x + (wp[j + 1].x - wp[j].x) * m; fy = wp[j].y + (wp[j + 1].y - wp[j].y) * m; }
        rip.push(clamp((s - 0.2) / 0.28));
        gd.push(clamp((s - 0.18) / 0.08) * (1 - clamp((s - 0.86) / 0.14)));
        if (s > 0.3) d = fr[j] + (fr[j + 1] - fr[j]) * inOut(clamp((s - 0.3) / 0.7));
      }
      var dash = (L * (1 - d)).toFixed(1);
      paths.forEach(function (p) { if (p) { p.style.strokeDasharray = L.toFixed(1) + ' ' + (L + 2).toFixed(1); p.style.strokeDashoffset = dash; } });
      if (head) {
        var hp = route.getPointAtLength(L * d);
        head.setAttribute('cx', hp.x.toFixed(1));
        head.setAttribute('cy', hp.y.toFixed(1));
        head.style.opacity = d > 0.002 && t < 0.47 ? 1 : 0;
      }
      if (finger) {
        finger.setAttribute('transform', 'translate(' + fx.toFixed(1) + ' ' + fy.toFixed(1) + ')');
        finger.style.opacity = fo.toFixed(3);
      }
      rips.forEach(function (c, i) {
        var r = rip[i] || 0;
        c.setAttribute('r', (6 + r * 24).toFixed(1));
        c.style.opacity = r > 0 && r < 1 ? (1 - r).toFixed(3) : 0;
        if (dots[i]) dots[i].style.opacity = clamp(r * 4).toFixed(3);
      });
      guides.forEach(function (g, i) { g.style.opacity = (gd[i] * 0.85).toFixed(3); });
      var text = nf.format(Math.round(KM * d * 10) / 10);
      if (text !== lastText) { num.textContent = text; lastText = text; }

      // Beat 2: what you will meet.
      var c = clamp((t - 0.465) / 0.15);
      if (comet) {
        var cp = route.getPointAtLength(L * c);
        comet.setAttribute('cx', cp.x.toFixed(1));
        comet.setAttribute('cy', cp.y.toFixed(1));
        comet.style.opacity = (clamp(c * 12) * (1 - clamp((c - 0.97) / 0.03))).toFixed(3);
      }
      pf.forEach(function (f, i) {
        var at = 0.465 + 0.15 * f - 0.01;
        set('--p' + i, back(clamp((t - at) / 0.06)));
      });

      // Beat 3: to your wrist.
      set('--k', inOut(clamp((t - 0.64) / 0.22)));
      set('--ph', out(clamp((t - 0.68) / 0.16)));
      set('--w', out(clamp((t - 0.72) / 0.16)));
      set('--turn', inOut(clamp((t - 0.87) / 0.08)));
      var bz = t > 0.93;
      if (bz !== buzz) { buzz = bz; sec.classList.toggle('pl-buzz', bz); }

      set('--b1', clamp(t / 0.46));
      set('--b2', clamp((t - 0.46) / 0.18));
      set('--b3', clamp((t - 0.64) / 0.31));
      var beat = t < 0.46 ? 0 : t < 0.64 ? 1 : 2;
      if (beat !== lastBeat) {
        lastBeat = beat;
        says.forEach(function (s, i) { s.classList.toggle('on', i === beat); });
        beats.forEach(function (s, i) { s.classList.toggle('on', i === beat); });
      }
    }

    function progress() {
      var r = run.getBoundingClientRect();
      var vh = window.innerHeight;
      var span = r.height - vh;
      if (span < 10) return 1;
      return clamp(-r.top / span);
    }

    var ticking = false, easing = false;
    function step() {
      easing = false;
      try {
        if (!root.classList.contains('motion')) { if (live) reset(); return; }
        var delta = target - shown;
        shown = Math.abs(delta) < 0.0008 ? target : shown + delta * 0.16;
        live = true;
        paint(shown);
        if (shown !== target) { easing = true; requestAnimationFrame(step); }
      } catch (e) { dead = true; reset(); }
    }
    function frame() {
      ticking = false;
      if (dead) return;
      try {
        if (!root.classList.contains('motion')) { if (live) reset(); return; }
        var r = run.getBoundingClientRect(), vh = window.innerHeight;
        if (r.bottom < -vh * 0.3 || r.top > vh * 1.3) return;   // far away: rest
        target = progress();
        if (!live) shown = target;
        if (!easing) { easing = true; requestAnimationFrame(step); }
      } catch (e) { dead = true; reset(); }
    }
    function request() {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(frame);
    }
    window.addEventListener('scroll', request, { passive: true });
    window.addEventListener('resize', request, { passive: true });
    window.addEventListener('load', request);
    request();
  } catch (e) { /* the final frame in the markup stays */ }
})();

/* scenes/widgets */
/* Widgets scene: scroll through the pin and the Home Screen straightens, the
   widgets fly in from depth one by one, then it dims to the Lock Screen.
   Writes custom properties only; CSS turns them into transforms. */
(function () {
  try {
    var root = document.documentElement;
    var sec = document.querySelector('.scene-widgets');
    if (!sec) return;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
    var pin = sec.querySelector('.wg-pin');
    var beats = [].slice.call(sec.querySelectorAll('.wg-beats li'));
    var watch = sec.querySelector('.wg-watch');
    var nums = [].slice.call(sec.querySelectorAll('.wg-num'));
    if (!pin) return;

    function clamp(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
    function seg(t, a, b) { return clamp((t - a) / (b - a)); }
    function out3(x) { return 1 - Math.pow(1 - x, 3); }
    function inOut(x) { return x < 0.5 ? 4 * x * x * x : 1 - Math.pow(-2 * x + 2, 3) / 2; }
    function back(x) { var c1 = 1.5, c3 = c1 + 1; return x <= 0 ? 0 : x >= 1 ? 1 : 1 + c3 * Math.pow(x - 1, 3) + c1 * Math.pow(x - 1, 2); }

    var last = {}, lastBeat = -1, lastWatch = null, lastNum = -1;
    function set(k, v) {
      var s = v.toFixed(4);
      if (last[k] === s) return;
      last[k] = s;
      sec.style.setProperty(k, s);
    }

    // Widget windows along the pin: [start, end].
    var W = [[0.06, 0.26], [0.13, 0.33], [0.22, 0.44], [0.31, 0.53]];

    function paint(t) {
      var a = inOut(seg(t, 0, 0.52));
      set('--tilt', 1 - a);
      set('--sh', Math.sin(Math.PI * seg(t, 0.12, 0.6)));
      for (var i = 0; i < 4; i++) {
        var p = seg(t, W[i][0], W[i][1]);
        set('--w' + (i + 1), back(p));
        set('--o' + (i + 1), clamp(p * 2.6));
      }
      var f1 = out3(seg(t, 0.2, 0.36));
      set('--f1', f1);
      set('--f3', out3(seg(t, 0.36, 0.52)));
      set('--f4', out3(seg(t, 0.45, 0.62)));
      set('--lk', inOut(seg(t, 0.62, 0.71)));
      set('--lc', out3(seg(t, 0.67, 0.79)));
      set('--l1', back(seg(t, 0.72, 0.84)));
      set('--l2', back(seg(t, 0.77, 0.89)));

      var n = Math.round(84 * f1);
      if (n !== lastNum) {
        lastNum = n;
        nums.forEach(function (el) { el.textContent = String(n); });
      }
      var b = t < 0.62 ? 0 : t < 0.9 ? 1 : 2;
      if (b !== lastBeat) {
        lastBeat = b;
        beats.forEach(function (li, j) { li.classList.toggle('on', j === b); });
      }
      var w = t > 0.88;
      if (w !== lastWatch && watch) { lastWatch = w; watch.classList.toggle('on', w); }
    }

    var ticking = false;
    function frame() {
      ticking = false;
      try {
        if (!root.classList.contains('motion')) { stop(); return; }
        var vh = window.innerHeight;
        var r = pin.getBoundingClientRect();
        if (r.bottom < -vh * 0.5 || r.top > vh * 1.5) return;
        var span = r.height - vh;
        var t = span > 0 ? clamp(-r.top / span) : 1;
        paint(t);
      } catch (e) { stop(); }
    }
    function request() {
      if (ticking) return;
      ticking = true;
      requestAnimationFrame(frame);
    }
    function stop() {
      sec.classList.remove('wg-live');
      ['--tilt', '--sh', '--w1', '--w2', '--w3', '--w4', '--o1', '--o2', '--o3', '--o4', '--f1', '--f3', '--f4', '--lk', '--lc', '--l1', '--l2']
        .forEach(function (k) { sec.style.removeProperty(k); });
      nums.forEach(function (el) { el.textContent = el.getAttribute('data-to'); });
      beats.forEach(function (li, j) { li.classList.toggle('on', j === 0); });
      window.removeEventListener('scroll', request);
      window.removeEventListener('resize', request);
    }

    // home.js adds .motion; wait for it if this file runs first.
    var started = false;
    function boot() {
      if (started || !root.classList.contains('motion')) return;
      started = true;
      paint(0);
      sec.classList.add('wg-live');
      window.addEventListener('scroll', request, { passive: true });
      window.addEventListener('resize', request, { passive: true });
      request();
    }
    boot();
    document.addEventListener('DOMContentLoaded', boot);
    window.addEventListener('load', function () { boot(); if (started) request(); });
  } catch (e) {
    try {
      var s = document.querySelector('.scene-widgets');
      if (s) {
        s.classList.remove('wg-live');
        [].slice.call(s.querySelectorAll('.wg-num')).forEach(function (el) { el.textContent = el.getAttribute('data-to'); });
      }
    } catch (e2) { /* static state stays */ }
  }
})();
